# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20161024_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hashId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
